language: ruby
sudo: false
cache: bundler # cache bundled gems from build to build
rvm:
  - 2.5.0

addons:
  postgresql: "9.4"

postgres:
  adapter: postgresql
  database: vhp
  username: postgres

services:
  - postgresql

before_install:
  - rm Gemfile.lock

before_script:
  - cp config/database.travis.yml config/database.yml
  - gem update --system
  - gem update bundler
  - psql -c "CREATE USER vhp WITH CREATEDB CREATEROLE SUPERUSER PASSWORD 'abcdefg'";

script:
  - bundle exec rails db:setup
  - bundle exec rails test

notifications:
  slack:
    secure: g4JiBvfCnCbwOQA94O2uCguSunjouUHTFfpKThtajDmKdLV1XmyKZLOkRMyfbW8ciS9tg/dq3so0kLNym55UwhQW7KbwqdVPgFZ8diIc34LqoUxWKi8QVGiLIOD3HZUfIZULJuAELVLyS35Zov+se9+NKh9EWoDclyQwfkNeRCxVbh+CSyZox6xc+AHW9NDo4D7b6HZt9uQKZJWwBCLq0h2IsmDHA+2BBRc/cyWAcztwLkEJmPdTc4HqYfwX/dHF9J38OGi0h3bqgc1nDmWBL7ao4E8KZwnepQoiDy8E563oFfxIqwZvEBj+wJtW/6e9CGLY7lRax/pNtsQnUHKGBCJN19bUdfyqfaoLHlYJEzTHqFt+e5PikFlJCfuP81/NpD5lE7yv3tQDzV111ihRoyd+bbwhrsUV13mzrewKOUhVwDZwbZzABPm77yK5z9trTtm5M9Zu3UxOoRcz+TXA9whxZuThv1Oz641V8/miwmVqFSfXwMcTYYgOQxe2jnZs7RN1d0M5BB0BhZ3z4vZSJFofi3Y72/R53JsmFFXz7FPnNx4hP0uiOWmm6SbRiQE4ghWUP89kikL/J2vLExbwxYZMifKw3l9z4Wjlxmf0vw+KN8nhGqOtcSNyKrXYM5mCDYaCYBQSk4EnY6rHVyitX/YAGJbk/xccTnSFONSOH2M=
    on_success: change
    on_failure: always
    on_pull_requests: false
