language: ruby
sudo: false
cache: bundler # cache bundled gems from build to build
rvm:
  - 2.3.3

addons:
  postgresql: "9.4"

postgres:
  adapter: postgresql
  database: vhp
  username: postgres

services:
  - postgresql

before_install:
  - rm Gemfile.lock

before_script:
  - cp config/database.travis.yml config/database.yml
  - gem update --system
  - gem update bundler
  - psql -c "CREATE USER vhp WITH CREATEDB CREATEROLE SUPERUSER PASSWORD 'abcdefg'";

script:
  - bundle exec rails db:setup
  - bundle exec rails test
