version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    volumes: 
      - shared_data:/var/shared/redis

  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - shared_data:/var/shared
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: vhp
      POSTGRES_PASSWORD: vhp

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 2345:80
    depends_on:
      - postgres

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
      RAILS_DB: postgres
      WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - postgres

  webpacker:
    image: vulnerability-history_app
    container_name: webpacker
    entrypoint: webpacker-entrypoint.sh
    command: ['ruby', 'bin/webpack-dev-server']
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    ports:
      - 3035:3035
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - 5900:5900

  test:
    image: vulnerability-history_app
    container_name: test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    ports:
      - 3005:3000
    stdin_open: true
    tty: true
    entrypoint: test-entrypoint.sh
    environment:
      - RAILS_ENV=test
      - RAILS_DB=postgres
      - RAILS_DOCKER=true
    depends_on:
      - postgres
      - selenium

volumes:
  gem_cache:
  pgadmin:
  postgres:  
  shared_data:
