version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    networks:
      - development
      - test
    volumes: 
      - shared_data:/var/shared/redis

  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - development
      - test
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 2345:80
    depends_on:
      - postgres

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - postgres

  webpacker:
    image: vulnerability-history_app
    container_name: webpacker
    entrypoint: webpacker-entrypoint.sh
    command: ['ruby', 'bin/webpack-dev-server']
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3035:3035

  selenium:
    image: selenium/standalone-chrome-debug:latest
    container_name: selenium
    networks:
      - development
      - test
    ports:
      - 5900:5900

  test:
    image: vulnerability-history_app
    container_name: test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3005:3000
    stdin_open: true
    tty: true
    entrypoint: test-entrypoint.sh
    command: ['rails', '-v']
    environment:
      RAILS_ENV: test
    depends_on:
      - postgres
      - selenium

networks:
  development:
  test:
volumes:
  gem_cache:
  pgadmin:
  postgres:  
  shared_data: