version: "3.9"

services:
  redis:
    image: redis:latest
    command: redis-server
    networks:
      - development
      - test
    volumes: 
      - shared_data:/var/shared/redis

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 2345:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  # if i ever figure out how to separate the services successfully
  # webpacker:
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 3035:3035
  #   # depends_on:
  #   #   - app

  app:
    build: .
    volumes:
      - .:/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    networks:
      - development
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    depends_on:
      - postgres
    
  # test:
  #   build: .
  #   volumes:
  #     - .:/var/app
  #     - shared_data:/var/shared
  #     - gem_cache:/usr/local/bundle/gems
  #     - node_modules:/app/node_modules
  #   networks:
  #     - test
  #   ports:
  #     - 3001:3000
  #   environment:
  #     RAILS_ENV: test
  #   depends_on:
  #     - postgres

networks:
  development:
  test:
volumes:
  gem_cache:
  node_modules:
  pgadmin:
  postgres:  
  shared_data: