openapi: 3.1.0
servers:
  - url: //api
info:
  title: Vulnerability History Project RESTful API
  description: |
    This read-only API allows detailed access to the VHP data.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /api/vulnerabilities:
    get:
      operationId: listVulnerabilities
      summary: /api/vulnerabilities
      description: Returns a non-detailed list of all vulnerabilities
      parameters:
        - name: short_descriptions
          description: |
            Should the descriptions be truncated? Mainly used in the VHP UI
          in: query
          required: false
          schema:
            type: boolean
        - name: limit
          description: |
            Limit the number of results
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          description: |
            Return a subset of the results, offset by this number
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
              examples:
                example1:
                  summary: /api/vulnerabilities (no parameters)
                  value: |
                    [
                      { id: 1472,
                        cve: "CVE-2017-5107",
                        announced: "2017-01-27T00:00:00.000Z",
                        upvotes: 50,
                        nickname: "Convoluted",
                        project_name: "Chromium",
                        subdomain: "chromium",
                        tag_json: [
                        {
                        id: 48,
                        importance: 1
                        },
                        {
                        id: 170,
                        importance: 0.45
                        },
                        {
                        id: 153,
                        importance: 0
                        },
                        {
                        id: 413,
                        importance: 0
                        },
                        {
                        id: 415,
                        importance: 0
                        },
                        {
                        id: 416,
                        importance: 0
                        }
                        ],
                        description: "User information leak via SVG. By rendering a FeConvolveMatrix SVG filter over
                        a target iframe and timing its execution an attacking page can extract pixel
                        values from a cross-origin page being iframe'd.
                        "
                      }
                    ]

        "400":
          description: Malformed request.
          content: {}
        "500":
          description: |
            Internal error. Please report these on our
            [issue tracker](https://github.com/VulnerabilityHistoryProject/vulnerability-history/issues).
          content: {}


  # /api/commits:
  #   get:
  #     summary: Returns
  #     description:
  #     parameters:
  #     responses:
  # /api/developers:
  #   get:
  #     summary:
  #     description:
  #     parameters:
  #     responses:
  # /api/filepaths:
  #   get:
  #     summary:
  #     description:
  #     parameters:
  #     responses:
  # /api/tags:
  #   get:
  #     summary:
  #     description:
  #     parameters:
  #     responses:
  # /api/articles:
  #   get:
  #     summary:
  #     description:
  #     parameters:
  #     responses:
  # /api/corpus:
  #   get:
  #     summary:
  #     description:
  #     parameters:
  #     responses:
  # /api/vulnerabilities/1/:
  # /api/vulnerabilities/1/events:
  # /api/commits/1/developer:
  # /api/filepaths/1:
  # /api/tags/1
  # /api/articles/1