# Setting up VHP? Do these steps
# 1. Make a copy of this file (secrets.default.yml), but rename it secrets.yml
# 2. Next to the database_password entry, mash the keyboard to make a long password. Be sure to not include any quotes or colons because... yml.
# 3. Copy that new password to the clipboard
# 4. Paste that new password into the OTHER database_password entry. They should both be the same.
# 5. Open up pgAdmin
# 6. Create a new user called "vhp"
#    * Give it the password you just made (under Privileges tab)
#    * Select the "Can Login" field (under Definition tab)
# 7. Create two databases named "vhp" and "vhp_test".
# 8. Make the owner of both of those databases "vhp".
# 9. In the command line at the top of this repo, run "rails secret"
# 10. Copy that long string into both secret_key_baes entries below
# 11. Go back to the README.md to finish the instructions

development:
  secret_key_base: # GENERATE with "rails secret"
  database_password: # PLACE YOUR VHP DATABASE PASSWORD HERE

test:
  secret_key_base: # REGENERATE  with "rake secret"
  database_password: # PLACE THE SAME database_password AS IN development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
