
name: T.H.E.S.E. MistakeBot

on:
  issues:
    types:
      - labeled

jobs:
  mistakebot:
    if: contains( github.event.issue.labels.*.name, 'to-err-is-human')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - name: Query for other mistake issues
        uses: octokit/graphql-action@v2.x
        id: count-err-issues
        with:
          query: |
           {
              repository(owner: "VulnerabilityHistoryProject", name: "vulnerability-history") {
                issues(labels: "to-err-is-human", first: 100) {
                  edges {
                    node {
                      id
                      number
                      title
                    }
                  }
                }
              }
            }
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: mistakes
          message: |
            :microscope: Hello, there! I'm MistakeBot.

            This is issue ${{ github.event.issue.number }} right?

            All "err" issues:

            ${{ steps.count-err-issues.outputs.data.repository.issues }}

            - [ ] Check this box (nothing happens at the moment)
            - [ ] Check this box (nothing happens at the moment)


