
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: vhp
          POSTGRES_DB: vhp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Set up Ruby deps cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: bundle exec rake
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - name: Install packages
      run: |
          yarn install --pure-lockfile
    - name: Setup test database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: vhp
      run: |
        bin/rails db:schema:load
    - name: Run tests
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: vhp
      run: |
        bin/rails test
